# Generated by Django 4.0.4 on 2022-11-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='likecount',
            field=models.IntegerField(default=0),
        ),
    ]
