# Generated by Django 4.0.4 on 2022-11-11 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_tweet_likecount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='user',
            new_name='sender',
        ),
    ]
